---
- name: Config instances 
  hosts: localhost
  vars:
    region: us-east-2
    key_inst: sertKey
    key_path: ./keys
    build_vm_ip: 0.0.0.0
    deploy_vm_ip: 0.0.0.0
  tasks:
    - name: Add build instance to host group
      add_host:
        hostname: "{{ build_vm_ip }}"
        groupname: build_host
        ansible_ssh_private_key_file: "{{ key_path }}/{{ key_inst }}.pem"
        ansible_ssh_user: ubuntu
    
    - name: Add deploy instance to host group
      add_host:
        hostname: "{{ deploy_vm_ip }}"
        groupname: deploy_host
        ansible_ssh_private_key_file: "{{ key_path }}/{{ key_inst }}.pem"
        ansible_ssh_user: ubuntu
 

- name: Build-server configuration
  hosts: build_host
  remote_user: root
  become: yes

  roles:
    - docker
    - builder


- name: Web-server configuration
  hosts: deploy_host
  become: yes

  roles:
    - docker
    - deployer
