FROM ubuntu:18.04

RUN apt update && apt install -y wget \
                                 zip \
                                 unzip \
                                 awscli 

RUN install software-properties-common -y \
    && apt-add-repository --yes --update ppa:ansible/ansible \
    && install ansible -y \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /home/agent/

RUN wget https://releases.hashicorp.com/terraform/0.15.3/terraform_0.15.3_linux_amd64.zip \
    && unzip terraform_0.15.3_linux_amd64.zip \
    && mv terraform /usr/bin/