FROM ubuntu:18.04

ENV TZ=Europe/Moscow

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt update && apt install -y wget \
                                 zip \
                                 unzip \
                                 awscli 

RUN apt install software-properties-common -y \
    && apt-add-repository --yes --update ppa:ansible/ansible \
    && apt install ansible -y \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /home/agent/

RUN wget https://releases.hashicorp.com/terraform/0.15.3/terraform_0.15.3_linux_amd64.zip \
    && unzip terraform_0.15.3_linux_amd64.zip \
    && mv terraform /usr/bin/

RUN export ANSIBLE_HOST_KEY_CHECKING=False