---
# tasks file for builder
- name: Ensure Dockerfile is copied
  copy:
    src: Dockerfile
    dest: {{ build_dir }}/Dockerfile
    
- name: Ensure in DockerHub is login
  docker_login:
    username: "{{ DockerHub_user }}"
    password: "{{ DockerHub_pass }}"

- name: Ensure Docker image is build
  docker_image:
    name: bakirovaasia/caucuscalculator
    build:
      path: "{{ build_dir }}"
    tag: latest
    push: yes
    source: build
  
  notify:
    - DockerHub logout
